name: Build, test and publish images

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  cancel-previous-runs:
    name: Cancel previous runs
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[ci skip]')"
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  build-test-push:
    name: Build, test and publish
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[ci skip]')"
    needs: cancel-previous-runs
    strategy:
      matrix:
        version: [ '7.2', '7.3' ]

    env:
      VERSION: "${{ matrix.version }}"
    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          make build VERSION=${VERSION}
          make -C dev build VERSION=${VERSION}
      - name: Test images
        run: |
          make test VERSION=${VERSION}
          make -C dev test VERSION=${VERSION}
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Publish images
        if: "github.event_name != 'pull_request'"
        run: |
          make push VERSION=${VERSION}
          make -C dev push VERSION=${VERSION}
